- title: Area Chair
  venues: 'EACL 2023 (area: Language Resource and Evaluation), EMNLP 2022 (area: NLP Applications), StarSEM 2022 (area: Commonsense reasoning and natural language understanding)'

- title: Reviewer (Journals)
  venues: Transactions of the Association for Computational Linguistics (TACL) 2019,2021. Computational Linguistics 2018.

- title: Reviewer (Conferences)
  venues: ACL Rolling Review (ARR) 2021, 2022. Annual Meeting of the Association for Computational Linguistics (ACL) 2018, 2019, 2020, 2021. Annual Meeting of the North American Chapter of the ACL (NAACL) 2018, 2019, 2021, 2022. Conference on Empirical Methods on Natural Language Processing (EMNLP) 2015, 2016, 2017, 2018, 2019, 2020, 2021. AAAI Conference on Artificial Intelligence 2020, 2021. International Joint Conferences on Artificial Intelligence (IJCAI) 2019, 2020, 2021. Conference on Computational Natural Language Learning (CoNLL) 2019, 2020. Conference of the European Chapter of the Association for Computational Linguistics (EACL) 2021,  Asia-Pacific Chapter of the Association for Computational Linguistics (AACL) 2020. International Joint Conference on Natural Language Processin (IJCNLP) 2017. International Conference on Computational Linguistics (COLING) 2014, 2016, 2018, 2020. International Conference on Spoken Language Translation (IWSLT) 2020.
  venues_short: ARR, ACL, NAACL, EMNLP, AAAI, IJCAI, CoNLL, EACL, AACL, IJCNLP, COLING, IWSLT.

- title: Reviewer (Workshops)
  venues: Methods for Optimizing and Evaluating Neural Language Generation (NeuralGen) 2019. Workshop on Innovative Use of NLP for Building Educational Applications (BEA) 2014, 2015, 2016, 2017, 2019, 2020. Workshop on Noisy User-generated Text (W-NUT) 2018, 2019 2020.
  venues_short: NeuralGen, BEA, W-NUT

